---
- name: setup wsl
  gather_facts: no
  hosts: localhost
  become: yes
  roles:
    - common
    - python
    - clojure
    - cl
    - golang
    - ruby
    - rust
    - nodejs
  vars:
    linux_dist: debian
    username: toracle
    home_dir: "/home/{{ username }}"

# clojure
# rust
# python3
# nodejs
# roswell
# emacs
# zsh
# omz
# mysql
# build-essential
