---
- name: setup wsl
  gather_facts: no
  hosts: localhost
  become: yes
  roles:
    - common
    - python
    - clojure
    - ruby

# clojure
# rust
# python3
# nodejs
# roswell
# emacs
# zsh
# omz
# mysql
# build-essential
