---
- name: setup wsl
  gather_facts: no
  hosts: localhost
  become: yes
  tasks:
    - name: zsh
      apt:
        name: zsh
    - name: install software-properties-common
      apt:
        name: software-properties-common
    - name: deadsnakes
      apt_repository:
        repo: ppa:deadsnakes/ppa
    - name: install build-essential
      apt:
        name: build-essential
    - name: emacs build deps
      apt:
        name: [libgtk-3-dev, libxpm-dev, libjpeg-dev, libgif-dev, libtiff-dev, gnutls-dev, libtinfo-dev, librsvg2-dev, liblcms2-dev, libgpm-dev, libm17n-dev, libotf-dev, libwebkit2gtk-4.0-dev]
    - name: install python3
      apt:
        name: [python3, python3-dev, python3-pip, python3.8, python3.8-dev]
    - name: openjdk-11
      apt:
        name: [openjdk-11-jdk]

# clojure
# rust
# python3
# nodejs
# roswell
# emacs
# zsh
# omz
# mysql
# build-essential
