- name: openjdk-11
  apt:
    name: [openjdk-11-jdk]

- name: install clojure
  shell:
    cmd: "curl -sL https://download.clojure.org/install/linux-install-1.10.1.536.sh | bash -"
    warn: no

- name: run clojure
  shell: clojure
  become: no
