- name: install software-properties-common
  apt:
    name: software-properties-common

- name: deadsnakes
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: install python3
  apt:
    name: [python3, python3-dev, python3-pip, python3.8, python3.8-dev]

- name: virtualenvwrapper
  pip:
    name: virtualenvwrapper
