- name: install software-properties-common
  apt:
    name: software-properties-common
  when: linux_dist == 'ubuntu'

- name: deadsnakes
  apt_repository:
    repo: ppa:deadsnakes/ppa
  when: linux_dist == 'ubuntu'

- name: install python3.8
  apt:
    name: [python3.8, python3.8-dev]
  when: linux_dist == 'ubuntu'

- name: install python3
  apt:
    name: [python3, python3-dev, python3-pip]

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper

- name: install awscli
  pip:
    name: awscli
