- name: install software-properties-common
  apt:
    name: software-properties-common
  when: ubuntu == true

- name: deadsnakes
  apt_repository:
    repo: ppa:deadsnakes/ppa
  when: ubuntu == true

- name: install python3.8
  apt:
    name: [python3.8, python3.8-dev]
  when: ubuntu == true

- name: install python3
  apt:
    name: [python3, python3-dev, python3-pip]

- name: virtualenvwrapper
  pip:
    name: virtualenvwrapper
