- name: zsh
  apt:
    name: zsh

- name: pass
  apt:
    name: pass

- name: install build-essential
  apt:
    name: build-essential

- name: emacs build deps
  apt:
    name: [libgtk-3-dev, libxpm-dev, libjpeg-dev, libgif-dev, libtiff-dev, gnutls-dev, libtinfo-dev, librsvg2-dev, liblcms2-dev, libgpm-dev, libm17n-dev, libotf-dev, libwebkit2gtk-4.0-dev]

- name: register emacs executable file
  stat:
    path: "/usr/local/bin/emacs"
  register: emacs_exe

- name: download emacs tarball
  unarchive:
    src: http://mirror.yongbok.net/gnu/emacs/emacs-26.3.tar.gz
    dest: /home/toracle
    remote_src: yes
  when: emacs_exe.stat.exists == False

- name: compile emacs
  shell: "cd /home/toracle/emacs-26.3; ./configure --with-xwidgets --with-x-toolkit=gtk3 --with-modules --with-mailutils; make; make install"
  when: emacs_exe.stat.exists == False

- name: download pandoc2
  get_url:
    url: https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
    dest: /home/toracle/pandoc-2.9.2.1-1-amd64.deb

- name: install pandoc2
  apt: deb="/home/toracle/pandoc-2.9.2.1-1-amd64.deb"

- name: install xfce4-terminal
  apt:
    name: xfce4-terminal

- name: download d2coding
  unarchive:
    src: https://github.com/naver/d2codingfont/blob/master/D2Coding-Ver1.3.2-20180524.zip?raw=true
    dest: /home/toracle
    remote_src: yes

- name: build font cache
  command: fc-cache -f -v

