- name: add backport
  template:
    src: backport-source
    dest: /etc/apt/sources.list.d/backport.list
  when: linux_dist == 'debian'

- name: apt update
  apt:
    update_cache: yes

- name: install unzip
  apt:
    name: unzip

- name: zsh
  apt:
    name: zsh

- name: install powerline fonts
  apt:
    name: fonts-powerline

- name: register omz
  stat:
    path: "{{ home_dir }}/.oh-my-zsh"
  register: omz_dir

- name: install omz
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  become: no
  when: omz_dir.stat.exists == False

- name: write zshrc
  template:
    src: zshrc.template
    dest: "{{ home_dir }}/.zshrc"
  become: no

- name: pass
  apt:
    name: pass

- name: install build-essential
  apt:
    name: build-essential

- name: emacs build deps
  apt:
    name: [libgtk-3-dev, libxpm-dev, libjpeg-dev, libgif-dev, libtiff-dev, gnutls-dev, libtinfo-dev, librsvg2-dev, liblcms2-dev, libgpm-dev, libm17n-dev, libotf-dev, libwebkit2gtk-4.0-dev, libmagickwand-dev, libxaw7-dev]

- name: register emacs executable file
  stat:
    path: "/usr/local/bin/emacs"
  register: emacs_exe

- name: download emacs tarball
  unarchive:
    src: http://mirror.yongbok.net/gnu/emacs/emacs-27.2.tar.gz
    dest: "{{ home_dir }}"
    remote_src: yes
  when: emacs_exe.stat.exists == False
  become: no

- name: compile emacs
  shell: "cd {{ home_dir }}/emacs-27.2; ./configure --with-x-toolkit=gtk2 --with-modules --with-mailutils --with-cairo; make;"
  when: emacs_exe.stat.exists == False
  become: no

- name: install emacs
  shell: "cd {{ home_dir }}/emacs-27.2; make install"
  when: emacs_exe.stat.exists == False

- name: install emacs configuration
  git:
    repo: 'git@github.com:toracle/.emacs.d.git'
    dest: "{{ home_dir }}/.emacs.d"
    accept_hostkey: yes
  become: no

- name: register pandoc2 deb file
  stat:
    path: "{{ home_dir }}/pandoc-2.9.2.1-1-amd64.deb"
  register: pandoc2_file

- name: download pandoc2
  get_url:
    url: https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
    dest: "{{ home_dir }}/pandoc-2.9.2.1-1-amd64.deb"
  when: pandoc2_file.stat.exists == False
  become: no

- name: install pandoc2
  apt: deb="{{ home_dir }}/pandoc-2.9.2.1-1-amd64.deb"

- name: install xfce4-terminal
  apt:
    name: xfce4-terminal

- name: .fonts directory
  file: 
    path: "{{ home_dir }}/.fonts"
    state: directory
  become: no

- name: register d2coding file
  stat:
    path: "{{ home_dir }}/.fonts/D2Coding"
  register: d2coding_dir

- name: download d2coding
  unarchive:
    src: https://github.com/naver/d2codingfont/blob/master/D2Coding-Ver1.3.2-20180524.zip?raw=true
    dest: "{{ home_dir }}/.fonts"
    remote_src: yes
  when: d2coding_dir.stat.exists == False
  become: no

- name: build font cache
  command: fc-cache -f -v

- name: install tmux
  apt:
    name: tmux

- name: install tmux.conf
  get_url:
    url: https://gist.githubusercontent.com/toracle/fc371f7d71ffd0962df7/raw/8fc86eba5e15d75294cec095f8b684204cc78c10/.tmux.conf
    dest: "{{ home_dir }}/.tmux.conf"

- name: install mariadbclient
  apt:
    name: [mariadb-client, libmariadbclient-dev]

- name: install libcurl4
  apt:
    name: [libcurl4-openssl-dev, libssl-dev]

- name: install ag
  apt:
    name: silversearcher-ag

- name: install groff
  apt:
    name: groff

- name: install graphviz
  apt:
    name: graphviz

- name: install gettext
  apt:
    name: gettext

- name: install cloc
  apt:
    name: cloc

- name: install install-info
  apt:
    name: install-info

- name: install isync
  apt:
    name: [isync, notmuch, w3m, libgmime-3.0-dev, libxapian-dev, guile-2.2-dev, html2text, xdg-utils]

- name: register mu executable file
  stat:
    path: "/usr/local/bin/mu"
  register: mu_exe

- name: download mu
  unarchive:
    src: https://github.com/djcb/mu/archive/1.4.13.tar.gz
    dest: "{{ home_dir }}"
    remote_src: yes
  become: no
  when: mu_exe.stat.exists == False

- name: autogen mu
  shell: "{{ home_dir }}/mu-1.4.13/autogen.sh"
  become: no
  when: mu_exe.stat.exists == False

- name: make mu
  shell: "cd {{ home_dir }}/mu-1.4.13/; make"
  become: no
  when: mu_exe.stat.exists == False

- name: make install mu
  shell: "cd {{ home_dir }}/mu-1.4.13/; make install"
  when: mu_exe.stat.exists == False
