- name: add repository
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common]
  when: not wsl

- name: add docker's gpg key (debian)
  shell:
    cmd: 'curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -'
    warn: false
  when: linux_dist == 'debian' and not wsl

- name: add docker's gpg key (ubuntu)
  shell:
    cmd: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -'
    warn: false
  when: linux_dist == 'ubuntu' and not wsl

- name: install fingerprint
  shell: apt-key fingerprint 0EBFCD88
  when: not wsl

- name: add docker repo (debian)
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  when: linux_dist == 'debian' and not wsl

- name: add docker repo (ubuntu)
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  when: linux_dist == 'ubuntu' and not wsl

- name: update apt
  apt:
    update_cache: yes

- name: install docker
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io]
  when: not wsl

- name: setup usermod
  shell: "usermod -aG docker {{ username }}"
  when: not wsl
