- name: install ruby
  apt:
    name: ruby-full
    default_release: buster-backports
  when: linux_dist == 'debian'

- name: install ruby
  apt:
    name: ruby-full
  when: linux_dist != 'debian'

- name: install cucumber
  gem:
    name: cucumber
    user_install: no
